[workspace]
members = [
    "examples/shared",
    "examples/hardcoded-csr",
    "examples/cookie-csr",
    "examples/navigator-languages-cookie-csr",
    "examples/navigator-languages-localstorage-csr",
]
