[package]
name = "navigator-languages-localstorage-csr"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.2.4"
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Navigator", "Storage"] }
