[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.2.4"
web-sys = {version = "0.3", features = ["HtmlDocument"] }
wasm-bindgen = "0.2"
console_log = "1"
log = "0.4"
